name: Android Release

#The trigger for when we want this android-release ci to be executed
on: push

#Jobs we want to execute
jobs:
  #Job we want to run
  build-and-test:
    runs-on: ubuntu-latest
    #Steps to run
    steps:
      #Checkout the repository code using v1 of the standard checkout Action
    - uses: actions/checkout@v1
      # Use the standard Java Action to setup Java
    - uses: actions/setup-java@v1
      #With gives us a way to pass parameters to an action in this case: actions/setup-java@v1
      with:
        # we want the latest Java 12
        java-version: '12.x'
      # Use the community Action to install Flutter
    - uses: subosito/flutter-action@v1
      with:
        # we want the stable channel
        flutter-version: '1.22.5'
        channel: 'stable'
    #Get Flutter Packages
    - name: Get All Flutter Packages
      run: flutter pub get
    # Build Yay!
    - name: Build Flutter APK
      run: flutter build apk


